version: '3.8'

services:

  #Java Services
  #Polling
  app-poll:
    image: t-bot
    restart: always
    container_name: t-bot
    env_file:
      - .env
    volumes:
      - ./logs:/app/log
    depends_on:
      - app-core
    networks:
      - app-network

  #Java Services
  #Core
  app-core:
    image: bot-core
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql/mysql-server:8.0
    restart: always
    container_name: mysql8
    ports:
      - "3306:3306"
    labels:
      environment: ${BOT_NAME}
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=test
    volumes:
      - ./dbdata:/var/lib/mysql/
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
