version: '3.8'

services:

  #Java Services
  #Puller
  app-pull:
    image: bot-pull
    restart: always
    container_name: botpull
    env_file:
      - .env
    volumes:
      - ./logs/puller:/app/log
    depends_on:
      - app-core
    networks:
      - app-network

  #Java Services
  #Core
  app-core:
    image: bot-core
    restart: always
    ports:
      - "8001-8020:8080"
    env_file:
      - .env
    volumes:
      - ./logs/core:/app/log
    depends_on:
      - db
    networks:
      - app-network
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}

  #MySQL Service
  db:
    image: mysql:8.0
    restart: always
    container_name: mysql8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=app
      - MYSQL_ROOT_HOST=${DB_HOST}
    env_file:
      - .env
    volumes:
      - ./dbdata:/var/lib/mysql/
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    name: app-network
    driver: bridge
